# Generated by Django 5.0.2 on 2024-06-07 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing_pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_type_name", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Workflows",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("workflow_name", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_name", models.CharField(max_length=500)),
                (
                    "action_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="landing_pages.actiontype",
                    ),
                ),
            ],
        ),
    ]
