# Generated by Django 5.0.2 on 2024-06-07 10:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing_pages", "0002_actiontype_workflows_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflows",
            name="created_by",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="workflows",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
